import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const isDarkMode = false;

export const metadata = {
  title: "D'visita",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={isDarkMode ? "dark" : "light"} lang="en">
      <head>
        <link rel="icon" href="./assets/next.svg" /> {/* Asegúrate de tener un favicon en public/favicon.ico */}
      </head>
      <body className={isDarkMode ? "dark" : "light"}>
        {children}
      </body>
    </html>
  );
}
